[package]
name = "iter-enum"
version = "1.0.1"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/iter-enum"
keywords = ["iterator", "derive", "enum"]
categories = ["no-std", "rust-patterns"]
exclude = ["/.*", "/tools"]
description = """
#[derive(Iterator, DoubleEndedIterator, ExactSizeIterator, Extend)] for enums.
"""

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
members = ["tests/doc"]

[lib]
proc-macro = true

[features]
# Enable to use `#[derive(ParallelIterator, IndexedParallelIterator, ParallelExtend)]`.
rayon = []

# Note: rayon is public dependency.
[dependencies]
derive_utils = { version = "0.11" }
quote = "1"
syn = "1"

[dev-dependencies]
macrotest = "1.0.8"
rayon_crate = { package = "rayon", version = "1" }
rustversion = "1"
