[package]
name = "iterator-enum"
version = "0.2.1"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/iterator-enum"
documentation = "https://docs.rs/iterator-enum/"
readme = "README.md"
keywords = ["iterator", "derive", "enum"]
categories = ["rust-patterns"]
description = "#[derive(Iterator, DoubleEndedIterator, ExactSizeIterator, FusedIterator, Extend)] for enums."

[lib]
proc-macro = true

[features]
# Make iterator implementation more effective.
try_trait = []
# #[derive(TrustedLen)]
trusted_len = []
# Implements `ExactSizeIterator::is_empty`.
exact_size_is_empty = []

rayon = []

[dependencies]
derive_utils = "0.9"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
rayon_crate = { version = "1.1", package = "rayon" }
