[package]
name = "iter-enum"
version = "0.2.6"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/iter-enum"
documentation = "https://docs.rs/iter-enum"
keywords = ["iterator", "derive", "enum"]
categories = ["rust-patterns"]
readme = "README.md"
description = """
#[derive(Iterator, DoubleEndedIterator, ExactSizeIterator, Extend)] for enums.
"""

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
members = ["tests/doc"]

[lib]
proc-macro = true

[features]
# #[derive(TrustedLen)]
trusted_len = []
# #[derive(ParallelIterator, IndexedParallelIterator, ParallelExtend)]
rayon = []

# NB: rayon is public dependencies.
[dependencies]
derive_utils = { version = "0.11" }
quote = "1"
syn = "1"

[dev-dependencies]
rayon_crate = { package = "rayon", version = "1" }
