[package]
name = "iterator-enum"
version = "0.2.2"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/iterator-enum"
documentation = "https://docs.rs/iterator-enum/"
keywords = ["iterator", "derive", "enum"]
categories = ["rust-patterns"]
readme = "README.md"
description = """
#[derive(Iterator, DoubleEndedIterator, ExactSizeIterator, Extend)] for enums.
"""

[lib]
proc-macro = true

[features]
# #[derive(TrustedLen)]
trusted_len = []
# #[derive(ParallelIterator, IndexedParallelIterator, ParallelExtend)]
rayon = []

[dependencies]
derive_utils = "0.9"
quote = "1.0"
syn = "1.0"

[dev-dependencies]
rayon_crate = { version = "1.2", package = "rayon" }
